module.exports = {
  DA: 'DA',
  IP: 'IP',
  SPS: 'SPS',
  DF: 'DF',
  FCCS: 'FCCS',
  XG: 'XG',
  TR: 'TR',
  RDPECS: 'RDPECS',
  RDPELS: 'RDPELS',
  BK: 'BK',
  INT: 'INT',
  OPA: 'OPA',
  NELS: 'NELS',
  FCLS: 'FCLS',
  RDTLS: 'RDTLS',
  NECS: 'NECS',
  RDTCP: 'RDTCP',
  P1: 'P1',
  EA: 'EA',
  RDTEXQ: 'RDTEXQ',
  EXNRDPE: 'ExNRDPE'
}
