#!/usr/bin/env sh
if [ -z "$(docker network ls --filter name=^ffc-pay$ --format={{.Name}})" ]; then
  echo "Creating ffc-pay Docker network"
  docker network create ffc-pay
fi

if [ -n "$(docker container ls --filter name=ffc-pay-dax-azurite --format={{.ID}})" ]; then
  echo "Azurite container already exists, skipping creation"
  args="--scale ffc-pay-dax-azurite=0"
fi

set -e
projectRoot="$(a="/$0"; a=${a%/*}; a=${a:-.}; a=${a#/}/; cd "$a/.." || return; pwd)"

cd "${projectRoot}"

docker-compose down
docker-compose -f docker-compose.migrate.yaml down
# Ensure container images are up to date
docker-compose -f docker-compose.migrate.yaml run database-up

docker-compose \
  -f docker-compose.yaml \
  -f docker-compose.override.yaml \
  -f docker-compose.link.yaml \
  up $@
